services:
  # The frontend application
  personal-website-frontend:
    container_name: personal-website-frontend
    build:
      context: ./frontend
      target: production
    depends_on:
      personal-website-api:
        condition: service_healthy
    networks:
      - default
      - network-global

  # The api application
  personal-website-api:
    image: personal-website-api
    container_name: personal-website-api
    build:
      context: ./api/
      target: production
    env_file:
      - ./.env
    volumes:
      - ./api/documents/:/app/documents/
    healthcheck:
      test: wget -qO- http://localhost/ping/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
      - network-global

  # The Postgres database with the pgvector extension for storing the embeddings
  postgres:
    container_name: personal-website-db
    image: pgvector/pgvector:pg17
    env_file:
      - ./.env
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: personal-website
  network-global:
    name: vm-load-balancer
    external: true
