services:
  # The frontend application
  personal-website-frontend:
    container_name: personal-website-frontend
    build:
      context: ./frontend
      target: development
    develop:
      watch:
        # Sync the entire frontend directory when any other file changes
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules
        # Rebuild the app container when the package.json file changes
        - action: rebuild
          path: ./frontend/package.json
          target: /app/package.json
        # Sync and restart the app container when the vite.config.js file changes
        - action: sync+restart
          path: ./frontend/vite.config.js
          target: /app/vite.config.js
    healthcheck:
      test: wget -qO- http://localhost:3000/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - 3000:3000
    depends_on:
      personal-website-api:
        condition: service_healthy

  # The api application
  personal-website-api:
    image: personal-website-api
    container_name: personal-website-api
    build:
      context: ./api/
      target: development
    env_file:
      - ./.env
    volumes:
      - ./api/:/app/
    healthcheck:
      test: wget -qO- http://localhost:8000/ping/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy

  # The Postgres database with the pgvector extension for storing the embeddings
  postgres:
    container_name: personal-website-db
    image: pgvector/pgvector:pg17
    env_file:
      - ./.env
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
